#ifndef GPU_OPENCL_KERNEL_H
#define GPU_OPENCL_KERNEL_H
/* AUTO-GENERATED from gpu_opencl_kernel.cl by scripts/gen_ocl_header.ps1.
 * Edit the .cl file instead and rebuild. */
static const char *OCL_SRC =
    "/* OpenCL port of the CPU estimator in tracer.c so the GPU frame matches:\n"
    " *   - path_radiance(): emission + ambient sky term + MIS direct light\n"
    " *     (GGX/Smith/Schlick BRDF, stochastic light-disk sampling) + BSDF\n"
    " *     sampling with Russian roulette, max_depth 4.\n"
    " *   - sky_color(): gradient + sun glow (glow^128) + sun disk (dot^9000).\n"
    " *   - material_albedo(): procedural textures (checker/grass/dirt/stone/\n"
    " *     wall/roof) + legacy ground-plane checker.\n"
    " *   - Sobol/Owen RNG with the same pixel seeds and draw order as the CPU.\n"
    " * Output is linear HDR; the host runs the exact CPU post chain\n"
    " * (exposure, bloom, Reinhard, sRGB) via rt_postprocess_hdr(). */\n"
    "\n"
    "#define PI_F 3.14159265f\n"
    "#define EPS 1e-5f\n"
    "#define MAX_DEPTH 4\n"
    "\n"
    "/* Per-frame scalar block (see OCL_FRAME_* in gpu_opencl.c). Every value the\n"
    " * trace kernels need that changes per frame travels through one buffer, so\n"
    " * kernel args are bound once and SetKernelArg never runs in the frame loop\n"
    " * (it costs ~3 ms per call on 51-arg kernels with the Gen9 driver). */\n"
    "#define F_CAM 0\n"
    "#define F_FWD 4\n"
    "#define F_RIGHT 8\n"
    "#define F_UP 12\n"
    "#define F_ASPECT 16\n"
    "#define F_W 20\n"
    "#define F_H 21\n"
    "#define F_SPP 22\n"
    "#define F_SAMPLE_BASE 23\n"
    "#define F_COUNTS 24\n"
    "#define F_TRI 28\n"
    "#define F_LIGHTS 29\n"
    "#define F_FOG 32\n"
    "#define F_SUN_DIR 36\n"
    "#define F_SUN_COL 40\n"
    "#define F_BMAT 44\n"
    "#define F_BEMI 48\n"
    "#define F_ACCUM 30\n"
    "#define FRAME_FLOATS 52\n"
    "\n"
    "struct Hit { float t; float3 n; int kind; int idx; };\n"
    "\n"
    "float clamp01(float x) { return clamp(x, 0.0f, 1.0f); }\n"
    "float lum(float3 c) { return 0.2126f * c.x + 0.7152f * c.y + 0.0722f * c.z; }\n"
    "\n"
    "/* ---- RNG: Sobol/Owen, identical to tracer.c ---- */\n"
    "uint sobol_owen(uint index, uint dimension) {\n"
    "    uint value = 0;\n"
    "    uint direction = 0x80000000u >> (dimension & 7u);\n"
    "    for (uint bit = 0; index != 0u && bit < 32u; bit++, index >>= 1) {\n"
    "        if ((index & 1u) != 0u) value ^= direction;\n"
    "        direction = (direction >> 1) ^ (0x80200003u & (uint)(-(int)(direction & 1u)));\n"
    "    }\n"
    "    value ^= value * 0x3d20adeau;\n"
    "    value ^= value >> 11;\n"
    "    value *= 0x05526c56u;\n"
    "    value ^= value >> 13;\n"
    "    return value;\n"
    "}\n"
    "float rng_float(uint *state) {\n"
    "    uint dimension = (*state) & 7u;\n"
    "    uint index = (*state) >> 3;\n"
    "    *state += 1u;\n"
    "    return ((float)sobol_owen(index + 1u, dimension) + 0.5f) / 4294967296.0f;\n"
    "}\n"
    "uint pixel_seed(int x, int y) {\n"
    "    uint seed = (uint)(x + 1) * 0x9e3779b9u;\n"
    "    seed ^= (uint)(y + 1) * 0x85ebca6bu;\n"
    "    seed ^= 0xc2b2ae35u;\n"
    "    return ((seed % 65521u) << 3) | 0u;\n"
    "}\n"
    "\n"
    "/* ---- BRDF ---- */\n"
    "float3 fresnel_schlick(float3 f0, float cos_theta) {\n"
    "    float m = 1.0f - clamp01(cos_theta);\n"
    "    float factor = m * m * m * m * m;\n"
    "    return f0 + (1.0f - f0) * factor;\n"
    "}\n"
    "float ggx_d(float no_h, float rough) {\n"
    "    float a = rough * rough, a2 = a * a, n2 = no_h * no_h;\n"
    "    float q = n2 * (a2 - 1.0f) + 1.0f;\n"
    "    return a2 / (PI_F * q * q);\n"
    "}\n"
    "float smith_g1(float no_v, float rough) {\n"
    "    float k = (rough + 1.0f) * (rough + 1.0f) * 0.125f;\n"
    "    return no_v / (no_v * (1.0f - k) + k);\n"
    "}\n"
    "float smith_vis(float no_l, float no_v, float rough) {\n"
    "    return smith_g1(no_l, rough) * smith_g1(no_v, rough);\n"
    "}\n"
    "float roughness_of(float shininess) {\n"
    "    return clamp(sqrt(2.0f / (shininess + 2.0f)), 0.045f, 1.0f);\n"
    "}\n"
    "void tangent_basis(float3 n, float3 *u, float3 *v) {\n"
    "    float3 helper = fabs(n.y) < 0.9f ? (float3)(0.0f, 1.0f, 0.0f) : (float3)(1.0f, 0.0f, 0.0f);\n"
    "    *u = normalize(cross(helper, n));\n"
    "    *v = cross(n, *u);\n"
    "}\n"
    "void brdf_eval(float3 albedo, float3 n, float3 view, float3 light_dir,\n"
    "               float reflection, float shininess, float *pdf, float3 *out_f) {\n"
    "    float no_l = fmax(dot(n, light_dir), 0.0f);\n"
    "    float no_v = fmax(dot(n, view), 0.0f);\n"
    "    if (no_l <= 0.0f || no_v <= 0.0f) { *pdf = 0.0f; *out_f = (float3)(0.0f); return; }\n"
    "    float3 h = normalize(light_dir + view);\n"
    "    float no_h = fmax(dot(n, h), 0.0f);\n"
    "    float vo_h = fmax(dot(view, h), 0.0f);\n"
    "    float rough = roughness_of(shininess);\n"
    "    float spec_probability = clamp01(0.25f + 0.70f * reflection);\n"
    "    float3 f0 = 0.04f * (1.0f - reflection) + albedo * reflection;\n"
    "    float3 f = fresnel_schlick(f0, vo_h);\n"
    "    float d = ggx_d(no_h, rough);\n"
    "    float g = smith_vis(no_l, no_v, rough);\n"
    "    float3 spec = f * (d * g / fmax(4.0f * no_l * no_v, 1e-5f));\n"
    "    float3 diff = albedo * (1.0f - f) / PI_F;\n"
    "    float diffuse_pdf = no_l / PI_F;\n"
    "    float spec_pdf = d * no_h / fmax(4.0f * vo_h, 1e-5f);\n"
    "    *pdf = (1.0f - spec_probability) * diffuse_pdf + spec_probability * spec_pdf;\n"
    "    *out_f = diff + spec;\n"
    "}\n"
    "float3 sample_cosine(float3 n, uint *rng, float *pdf) {\n"
    "    float r = sqrt(rng_float(rng));\n"
    "    float phi = 2.0f * PI_F * rng_float(rng);\n"
    "    float z = sqrt(fmax(1.0f - r * r, 0.0f));\n"
    "    float3 u, v;\n"
    "    tangent_basis(n, &u, &v);\n"
    "    float3 d = u * (r * cos(phi)) + v * (r * sin(phi)) + n * z;\n"
    "    *pdf = z / PI_F;\n"
    "    return normalize(d);\n"
    "}\n"
    "float3 sample_ggx(float3 n, float rough, uint *rng, float *pdf) {\n"
    "    float alpha = rough * rough;\n"
    "    float phi = 2.0f * PI_F * rng_float(rng);\n"
    "    float u = rng_float(rng);\n"
    "    float cos_theta = sqrt((1.0f - u) / (1.0f + (alpha * alpha - 1.0f) * u));\n"
    "    float sin_theta = sqrt(fmax(1.0f - cos_theta * cos_theta, 0.0f));\n"
    "    float3 t, b;\n"
    "    tangent_basis(n, &t, &b);\n"
    "    float3 h = normalize(t * (sin_theta * cos(phi)) + b * (sin_theta * sin(phi)) + n * cos_theta);\n"
    "    *pdf = ggx_d(fmax(dot(n, h), 0.0f), rough) / fmax(4.0f * fabs(dot(h, n)), 1e-5f);\n"
    "    return h;\n"
    "}\n"
    "float3 sample_bsdf(float3 albedo, float3 n, float3 view, float reflection,\n"
    "                   float shininess, uint *rng, float3 *direction, float *pdf) {\n"
    "    float rough = roughness_of(shininess);\n"
    "    float spec_probability = clamp01(0.25f + 0.70f * reflection);\n"
    "    if (rng_float(rng) < spec_probability) {\n"
    "        float3 h = sample_ggx(n, rough, rng, pdf);\n"
    "        *direction = normalize(h * (2.0f * dot(view, h)) - view);\n"
    "    } else {\n"
    "        *direction = sample_cosine(n, rng, pdf);\n"
    "    }\n"
    "    if (dot(n, *direction) <= 0.0f) { *pdf = 0.0f; return (float3)(0.0f); }\n"
    "    float3 f;\n"
    "    brdf_eval(albedo, n, view, *direction, reflection, shininess, pdf, &f);\n"
    "    return f;\n"
    "}\n"
    "\n"
    "/* ---- procedural albedo (material_albedo port) ---- */\n"
    "float tex_hash(int x, int y, int z) {\n"
    "    uint n = (uint)x * 374761393u;\n"
    "    n += (uint)y * 668265263u;\n"
    "    n += (uint)z * 2147483647u;\n"
    "    n = (n ^ (n >> 13)) * 1274126177u;\n"
    "    n ^= n >> 16;\n"
    "    return (float)(n & 0xffffu) / 65535.0f;\n"
    "}\n"
    "float3 material_albedo(float3 base_albedo, float4 texA, float4 texB, float3 p) {\n"
    "    int ttype = (int)texA.x;\n"
    "    if (ttype == 0) return base_albedo;\n"
    "    float scale = texA.y > 0.0f ? texA.y : 1.0f;\n"
    "    int ix = (int)floor(p.x * scale);\n"
    "    int iy = (int)floor(p.y * scale);\n"
    "    int iz = (int)floor(p.z * scale);\n"
    "    float value = tex_hash(ix, iy, iz);\n"
    "    float3 alternate = texB.xyz;\n"
    "    if (ttype == 1) {                       /* CHECKER */\n"
    "        value = ((ix + iz) & 1) ? 1.0f : 0.0f;\n"
    "    } else if (ttype == 2) {                /* GRASS */\n"
    "        value = 0.72f + 0.28f * value;\n"
    "    } else if (ttype == 3) {                /* DIRT */\n"
    "        value = 0.68f + 0.32f * value;\n"
    "    } else if (ttype == 4) {                /* STONE */\n"
    "        value = 0.70f + 0.30f * value;\n"
    "    } else if (ttype == 5) {                /* WALL */\n"
    "        value = 0.82f + 0.18f * value;\n"
    "    } else if (ttype == 6) {                /* ROOF */\n"
    "        value = (((ix + iz * 3) & 3) == 0) ? 0.48f : (0.78f + 0.22f * value);\n"
    "    }\n"
    "    value = 1.0f - texA.z + texA.z * value;\n"
    "    return base_albedo * value + alternate * (1.0f - value);\n"
    "}\n"
    "\n"
    "/* ---- geometry ---- */\n"
    "float2 sph_hit(const float4 s, const float3 ro, const float3 rd) {\n"
    "    float3 oc = ro - s.xyz;\n"
    "    float b = dot(oc, rd);\n"
    "    float c = dot(oc, oc) - s.w * s.w;\n"
    "    float disc = b * b - c;\n"
    "    if (disc < 0.0f) return (float2)(-1.0f, -1.0f);\n"
    "    float sq = sqrt(disc);\n"
    "    float t0 = -b - sq, t1 = -b + sq;\n"
    "    if (t0 > EPS) return (float2)(t0, t1);\n"
    "    if (t1 > EPS) return (float2)(t1, t0);\n"
    "    return (float2)(-1.0f, -1.0f);\n"
    "}\n"
    "float2 box_hit(const float4 mn, const float4 mx, const float3 ro, const float3 rd) {\n"
    "    float3 inv = 1.0f / rd;\n"
    "    float3 t0 = (mn.xyz - ro) * inv;\n"
    "    float3 t1 = (mx.xyz - ro) * inv;\n"
    "    float3 tn = fmin(t0, t1), tf = fmax(t0, t1);\n"
    "    float near = fmax(fmax(tn.x, tn.y), tn.z);\n"
    "    float far = fmin(fmin(tf.x, tf.y), tf.z);\n"
    "    if (near > far || far < EPS) return (float2)(-1.0f, -1.0f);\n"
    "    return (float2)(near > EPS ? near : far, near);\n"
    "}\n"
    "float2 cyl_hit(const float4 base, const float2 ht, const float3 ro, const float3 rd) {\n"
    "    float r = base.w;\n"
    "    float2 d = ro.xz - base.xz;\n"
    "    float a = rd.x * rd.x + rd.z * rd.z;\n"
    "    float b = 2.0f * dot(d, rd.xz);\n"
    "    float c = dot(d, d) - r * r;\n"
    "    float best = 1e30f;\n"
    "    int found = 0, side = 0;\n"
    "    if (a > 1e-12f) {\n"
    "        float disc = b * b - 4.0f * a * c;\n"
    "        if (disc >= 0.0f) {\n"
    "            float q = sqrt(disc);\n"
    "            float t0 = (-b - q) / (2.0f * a), t1 = (-b + q) / (2.0f * a);\n"
    "            if (t0 > EPS && t0 < best) { float y = ro.y + rd.y * t0; if (y >= base.y && y <= ht.x) { best = t0; found = 1; side = 1; } }\n"
    "            if (t1 > EPS && t1 < best) { float y = ro.y + rd.y * t1; if (y >= base.y && y <= ht.x) { best = t1; found = 1; side = 1; } }\n"
    "        }\n"
    "    }\n"
    "    if (fabs(rd.y) > 1e-9f) {\n"
    "        float t = (base.y - ro.y) / rd.y;\n"
    "        float2 q = ro.xz + rd.xz * t - base.xz;\n"
    "        if (t > EPS && dot(q, q) <= r * r && t < best) { best = t; found = 1; side = 0; }\n"
    "        t = (ht.x - ro.y) / rd.y;\n"
    "        q = ro.xz + rd.xz * t - base.xz;\n"
    "        if (t > EPS && dot(q, q) <= r * r && t < best) { best = t; found = 1; side = 0; }\n"
    "    }\n"
    "    return found ? (float2)(best, (float)side) : (float2)(-1.0f, 0.0f);\n"
    "}\n"
    "float plane_hit(const float y, const float3 ro, const float3 rd) {\n"
    "    if (fabs(rd.y) < 1e-9f) return -1.0f;\n"
    "    float t = (y - ro.y) / rd.y;\n"
    "    return t > EPS ? t : -1.0f;\n"
    "}\n"
    "float3 tri_fetch(__global const float *tris, const int tri, const int k) {\n"
    "    return vload3(tri * 3 + k, tris);\n"
    "}\n"
    "float tri_hit(__global const float *tris, const int tri, const float3 ro, const float3 rd) {\n"
    "    float3 v0 = tri_fetch(tris, tri, 0);\n"
    "    float3 e1 = tri_fetch(tris, tri, 1);\n"
    "    float3 e2 = tri_fetch(tris, tri, 2);\n"
    "    float3 p = cross(rd, e2);\n"
    "    float det = dot(e1, p);\n"
    "    if (fabs(det) < 1e-8f) return -1.0f;\n"
    "    float inv = 1.0f / det;\n"
    "    float3 tv = ro - v0;\n"
    "    float u = dot(tv, p) * inv;\n"
    "    if (u < 0.0f || u > 1.0f) return -1.0f;\n"
    "    float3 q = cross(tv, e1);\n"
    "    float v = dot(rd, q) * inv;\n"
    "    if (v < 0.0f || u + v > 1.0f) return -1.0f;\n"
    "    float t = dot(e2, q) * inv;\n"
    "    return t > EPS ? t : -1.0f;\n"
    "}\n"
    "\n"
    "/* ---- uniform grid over the bunny triangles (built once on the host) ----\n"
    " * grid_a:  (origin.xyz, cell_size)\n"
    " * grid_dims: (nx, ny, nz, 0);  CSR cells: grid_off[n+1], grid_tri[].\n"
    " * Returns triangle index of the closest hit within max_t, -1 if none.\n"
    " * When occlusion_only, returns early on any hit. */\n"
    "int grid_traverse(const float3 ro, const float3 rd, const float max_t,\n"
    "                  const bool occlusion_only, float *best_t_out,\n"
    "                  __global const float4 *grid_a, __global const uint4 *grid_dims,\n"
    "                  __global const uint *grid_off, __global const uint *grid_tri,\n"
    "                  __global const float *tris) {\n"
    "    *best_t_out = 1e30f;\n"
    "    if (grid_dims[0].x == 0u) return -1;\n"
    "    float3 origin = grid_a[0].xyz;\n"
    "    float cell = grid_a[0].w;\n"
    "    int3 dims = (int3)((int)grid_dims[0].x, (int)grid_dims[0].y, (int)grid_dims[0].z);\n"
    "    float3 inv = 1.0f / rd;\n"
    "    float3 t0s = (origin - ro) * inv;\n"
    "    float3 t1s = (origin + (convert_float3(dims) * cell) - ro) * inv;\n"
    "    float3 tn3 = fmin(t0s, t1s), tf3 = fmax(t0s, t1s);\n"
    "    float t_entry = fmax(fmax(tn3.x, tn3.y), tn3.z);\n"
    "    float t_exit = fmin(fmin(tf3.x, tf3.y), tf3.z);\n"
    "    if (t_entry > t_exit || t_exit < EPS || t_entry > max_t) return -1;\n"
    "\n"
    "    float t_start = fmax(t_entry, 0.0f);\n"
    "    float3 p = ro + rd * t_start;\n"
    "    int3 cell_i = convert_int3(floor((p - origin) / cell));\n"
    "    cell_i = clamp(cell_i, (int3)0, dims - 1);\n"
    "    int3 step = convert_int3(sign(rd));\n"
    "    float3 t_delta = fabs(cell * inv);\n"
    "    /* distance along the ray to the next boundary per axis */\n"
    "    float3 t_next;\n"
    "    if (fabs(rd.x) < 1e-9f) t_next.x = 1e30f;\n"
    "    else { float b = origin.x + (convert_float3(cell_i).x + (step.x > 0 ? 1.0f : 0.0f)) * cell; t_next.x = (b - ro.x) / rd.x; }\n"
    "    if (fabs(rd.y) < 1e-9f) t_next.y = 1e30f;\n"
    "    else { float b = origin.y + (convert_float3(cell_i).y + (step.y > 0 ? 1.0f : 0.0f)) * cell; t_next.y = (b - ro.y) / rd.y; }\n"
    "    if (fabs(rd.z) < 1e-9f) t_next.z = 1e30f;\n"
    "    else { float b = origin.z + (convert_float3(cell_i).z + (step.z > 0 ? 1.0f : 0.0f)) * cell; t_next.z = (b - ro.z) / rd.z; }\n"
    "\n"
    "    float best_t = fmin(max_t, t_exit);\n"
    "    int best_tri = -1;\n"
    "    for (;;) {\n"
    "        /* z-major, matching the host CSR builder (z*gy*gx + y*gx + x) */\n"
    "        uint ci = (uint)(cell_i.z * dims.y * dims.x + cell_i.y * dims.x + cell_i.x);\n"
    "        uint off = grid_off[ci], end = grid_off[ci + 1u];\n"
    "        for (; off < end; off++) {\n"
    "            int tri = (int)grid_tri[off];\n"
    "            float t = tri_hit(tris, tri, ro, rd);\n"
    "            if (t > 0.0f && t < best_t) {\n"
    "                best_t = t;\n"
    "                best_tri = tri;\n"
    "                if (occlusion_only) return best_tri;\n"
    "            }\n"
    "        }\n"
    "        int axis = (t_next.x < t_next.y)\n"
    "            ? ((t_next.x < t_next.z) ? 0 : 2)\n"
    "            : ((t_next.y < t_next.z) ? 1 : 2);\n"
    "        float tn = axis == 0 ? t_next.x : (axis == 1 ? t_next.y : t_next.z);\n"
    "        if (tn > best_t) break;\n"
    "        if (axis == 0) { cell_i.x += step.x; t_next.x += t_delta.x; if (cell_i.x < 0 || cell_i.x >= dims.x) break; }\n"
    "        else if (axis == 1) { cell_i.y += step.y; t_next.y += t_delta.y; if (cell_i.y < 0 || cell_i.y >= dims.y) break; }\n"
    "        else { cell_i.z += step.z; t_next.z += t_delta.z; if (cell_i.z < 0 || cell_i.z >= dims.z) break; }\n"
    "    }\n"
    "    *best_t_out = best_t;\n"
    "    return best_tri;\n"
    "}\n"
    "\n"
    "/* __GRID_CONT__ */\n"
    "\n"
    "struct Hit trace(const float3 ro, const float3 rd, const int4 counts,\n"
    "                 __global const float4 *sph,\n"
    "                 __global const float4 *box_min, __global const float4 *box_max,\n"
    "                 __global const float4 *cyl_b, __global const float4 *cyl_h,\n"
    "                 __global const float4 *plane_pos,\n"
    "                 const int tri_count, __global const float *tris,\n"
    "                 __global const float4 *grid_a, __global const uint4 *grid_dims,\n"
    "                 __global const uint *grid_off, __global const uint *grid_tri) {\n"
    "    struct Hit h;\n"
    "    h.t = 1e30f; h.kind = -1; h.idx = -1; h.n = (float3)(0.0f, 1.0f, 0.0f);\n"
    "    for (int i = 0; i < counts.x; i++) {\n"
    "        float2 t = sph_hit(sph[i], ro, rd);\n"
    "        if (t.x > 0.0f && t.x < h.t) {\n"
    "            float3 p = ro + rd * t.x;\n"
    "            h.t = t.x; h.n = normalize(p - sph[i].xyz); h.kind = 0; h.idx = i;\n"
    "        }\n"
    "    }\n"
    "    for (int i = 0; i < counts.y; i++) {\n"
    "        float2 t = box_hit(box_min[i], box_max[i], ro, rd);\n"
    "        if (t.x > 0.0f && t.x < h.t) {\n"
    "            float3 p = ro + rd * t.x;\n"
    "            float3 c = 0.5f * (box_min[i].xyz + box_max[i].xyz);\n"
    "            float3 d = (p - c) / fmax(box_max[i].xyz - c, (float3)(1e-6f));\n"
    "            float3 ad = fabs(d);\n"
    "            float3 n = (float3)(0.0f);\n"
    "            if (ad.x >= ad.y && ad.x >= ad.z) n = (float3)(sign(d.x), 0.0f, 0.0f);\n"
    "            else if (ad.y >= ad.z) n = (float3)(0.0f, sign(d.y), 0.0f);\n"
    "            else n = (float3)(0.0f, 0.0f, sign(d.z));\n"
    "            h.t = t.x; h.n = n; h.kind = 1; h.idx = i;\n"
    "        }\n"
    "    }\n"
    "    for (int i = 0; i < counts.z; i++) {\n"
    "        float2 t = cyl_hit(cyl_b[i], cyl_h[i].xy, ro, rd);\n"
    "        if (t.x > 0.0f && t.x < h.t) {\n"
    "            float3 p = ro + rd * t.x;\n"
    "            h.t = t.x;\n"
    "            if (t.y > 0.5f) {\n"
    "                h.n = normalize((float3)(p.x - cyl_b[i].x, 0.0f, p.z - cyl_b[i].z));\n"
    "            } else {\n"
    "                h.n = (float3)(0.0f, (p.y - cyl_b[i].y > 0.0f) ? 1.0f : -1.0f, 0.0f);\n"
    "            }\n"
    "            h.kind = 4; h.idx = i;\n"
    "        }\n"
    "    }\n"
    "    for (int i = 0; i < counts.w; i++) {\n"
    "        float t = plane_hit(plane_pos[i].w, ro, rd);\n"
    "        if (t > 0.0f && t < h.t) {\n"
    "            h.t = t; h.n = (float3)(0.0f, ro.y > plane_pos[i].w ? 1.0f : -1.0f, 0.0f);\n"
    "            h.kind = 2; h.idx = i;\n"
    "        }\n"
    "    }\n"
    "    float mesh_t;\n"
    "    int tri = grid_traverse(ro, rd, h.t, false, &mesh_t,\n"
    "                            grid_a, grid_dims, grid_off, grid_tri, tris);\n"
    "    if (tri >= 0 && mesh_t < h.t) {\n"
    "        h.t = mesh_t;\n"
    "        h.n = normalize(cross(tri_fetch(tris, tri, 1), tri_fetch(tris, tri, 2)));\n"
    "        h.kind = 3; h.idx = tri;\n"
    "    }\n"
    "    return h;\n"
    "}\n"
    "\n"
    "/* occluded(): shadow / occlusion test (rt_trace equivalent) */\n"
    "bool occluded(const float3 ro, const float3 rd, const float max_t, const int4 counts,\n"
    "              __global const float4 *sph,\n"
    "              __global const float4 *box_min, __global const float4 *box_max,\n"
    "              __global const float4 *cyl_b, __global const float4 *cyl_h,\n"
    "              __global const float4 *plane_pos,\n"
    "              const int tri_count, __global const float *tris,\n"
    "              __global const float4 *grid_a, __global const uint4 *grid_dims,\n"
    "              __global const uint *grid_off, __global const uint *grid_tri) {\n"
    "    for (int i = 0; i < counts.x; i++) {\n"
    "        float2 t = sph_hit(sph[i], ro, rd);\n"
    "        if (t.x > 0.0f && t.x < max_t) return true;\n"
    "    }\n"
    "    for (int i = 0; i < counts.y; i++) {\n"
    "        float2 t = box_hit(box_min[i], box_max[i], ro, rd);\n"
    "        if (t.x > 0.0f && t.x < max_t) return true;\n"
    "    }\n"
    "    for (int i = 0; i < counts.z; i++) {\n"
    "        float2 t = cyl_hit(cyl_b[i], cyl_h[i].xy, ro, rd);\n"
    "        if (t.x > 0.0f && t.x < max_t) return true;\n"
    "    }\n"
    "    for (int i = 0; i < counts.w; i++) {\n"
    "        float t = plane_hit(plane_pos[i].w, ro, rd);\n"
    "        if (t > 0.0f && t < max_t) return true;\n"
    "    }\n"
    "    float mesh_t;\n"
    "    int tri = grid_traverse(ro, rd, max_t, true, &mesh_t,\n"
    "                            grid_a, grid_dims, grid_off, grid_tri, tris);\n"
    "    (void)mesh_t;\n"
    "    /* traversal already rejects hits beyond max_t */\n"
    "    return tri >= 0;\n"
    "}\n"
    "\n"
    "/* sky_color port: gradient + sun glow (8 squarings = glow^256 ~ ^200) +\n"
    " * compact sun disk (dot^9000). sun_dir/sun_col are precomputed on the host\n"
    " * from scene light/camera/light_rgb(). */\n"
    "float3 sky_color(const float3 rd, const float4 sun_dir, const float4 sun_col) {\n"
    "    float t = clamp(rd.y * 0.5f + 0.5f, 0.0f, 1.0f);\n"
    "    float3 horizon = (float3)(0.75f, 0.82f, 0.90f);\n"
    "    float3 zenith = (float3)(0.25f, 0.45f, 0.78f);\n"
    "    float3 c = horizon * (1.0f - t) + zenith * t;\n"
    "    float glow = fmax(dot(rd, sun_dir.xyz), 0.0f);\n"
    "    float glow2 = glow * glow;\n"
    "    glow2 *= glow2; glow2 *= glow2; glow2 *= glow2;\n"
    "    glow2 *= glow2; glow2 *= glow2; glow2 *= glow2;\n"
    "    float sun_disk = powr(fmax(dot(rd, sun_dir.xyz), 0.0f), 9000.0f);\n"
    "    c += sun_col.xyz * (glow2 * 0.6f + sun_disk * 120.0f);\n"
    "    return c;\n"
    "}\n"
    "\n"
    "/* sample_direct_light port: stochastic light-disk sampling, shadow ray,\n"
    " * BRDF eval and MIS weight. */\n"
    "float3 sample_direct_light(const float3 p, const float3 n, const float3 view,\n"
    "                           const float3 albedo, const float reflection,\n"
    "                           const float shininess, uint *rng,\n"
    "                           const int4 counts, const int light_count,\n"
    "                           __global const float4 *lpos, __global const float4 *lcol,\n"
    "                           __global const float4 *lrad,\n"
    "                           __global const float4 *sph,\n"
    "                           __global const float4 *box_min, __global const float4 *box_max,\n"
    "                           __global const float4 *cyl_b, __global const float4 *cyl_h,\n"
    "                           __global const float4 *plane_pos,\n"
    "                           const int tri_count, __global const float *tris,\n"
    "                           __global const float4 *grid_a, __global const uint4 *grid_dims,\n"
    "                           __global const uint *grid_off, __global const uint *grid_tri) {\n"
    "    if (light_count <= 0) return (float3)(0.0f);\n"
    "    float3 result = (float3)(0.0f);\n"
    "    for (int li = 0; li < light_count; li++) {\n"
    "        float3 lp = lpos[li].xyz;\n"
    "        float radius = lrad[li].x;\n"
    "        if (radius > 0.0f) {\n"
    "            float3 axis = normalize(lp - p);\n"
    "            float3 u, v;\n"
    "            tangent_basis(axis, &u, &v);\n"
    "            float r = sqrt(rng_float(rng)) * radius;\n"
    "            float phi = 2.0f * PI_F * rng_float(rng);\n"
    "            lp += u * (r * cos(phi)) + v * (r * sin(phi));\n"
    "        }\n"
    "        float3 delta = lp - p;\n"
    "        float distance_sq = dot(delta, delta);\n"
    "        if (distance_sq <= 1e-6f) continue;\n"
    "        float distance = sqrt(distance_sq);\n"
    "        float3 l = delta / distance;\n"
    "        float no_l = fmax(dot(n, l), 0.0f);\n"
    "        if (no_l <= 0.0f) continue;\n"
    "        if (occluded(p + n * 1e-3f, l, distance, counts, sph, box_min, box_max,\n"
    "                     cyl_b, cyl_h, plane_pos, tri_count, tris,\n"
    "                     grid_a, grid_dims, grid_off, grid_tri)) continue;\n"
    "        float bsdf_pdf;\n"
    "        float3 f;\n"
    "        brdf_eval(albedo, n, view, l, reflection, shininess, &bsdf_pdf, &f);\n"
    "        if (bsdf_pdf <= 0.0f) continue;\n"
    "        float light_pdf = 1.0f;\n"
    "        if (radius > 0.0f) {\n"
    "            float area = PI_F * radius * radius;\n"
    "            float facing = fmax(dot(-l, normalize(lpos[li].xyz - p)), 0.05f);\n"
    "            light_pdf = distance_sq / (area * facing);\n"
    "        }\n"
    "        float mis = radius > 0.0f\n"
    "            ? (light_pdf * light_pdf) / (light_pdf * light_pdf + bsdf_pdf * bsdf_pdf)\n"
    "            : 1.0f;\n"
    "        float3 incoming = lcol[li].xyz * (lpos[li].w / (4.0f * PI_F * distance_sq));\n"
    "        result += f * incoming * (no_l * mis / fmax(light_pdf, 1e-5f));\n"
    "    }\n"
    "    return result;\n"
    "}\n"
    "\n"
    "/* per-object material fetch:\n"
    " *  mat: (albedo.xyz, reflection)  emi: (emission.xyz, shininess)\n"
    " *  texA: (texture_type, texture_scale, texture_strength, 0)\n"
    " *  texB: (texture_color.xyz, 0) */\n"
    "void fetch_material(const int kind, const int idx,\n"
    "                    __global const float4 *sph_mat, __global const float4 *sph_emi,\n"
    "                    __global const float4 *sph_texA, __global const float4 *sph_texB,\n"
    "                    __global const float4 *box_mat, __global const float4 *box_emi,\n"
    "                    __global const float4 *box_texA, __global const float4 *box_texB,\n"
    "                    __global const float4 *cyl_mat, __global const float4 *cyl_emi,\n"
    "                    __global const float4 *cyl_texA, __global const float4 *cyl_texB,\n"
    "                    __global const float4 *plane_mat, __global const float4 *plane_emi,\n"
    "                    __global const float4 *plane_texA, __global const float4 *plane_texB,\n"
    "                    const float4 bunny_mat, const float4 bunny_emi,\n"
    "                    float3 *albedo_base, float3 *emission, float *reflection,\n"
    "                    float *shininess, float4 *texA, float4 *texB) {\n"
    "    if (kind == 0) {\n"
    "        *albedo_base = sph_mat[idx].xyz; *emission = sph_emi[idx].xyz;\n"
    "        *reflection = sph_mat[idx].w; *shininess = sph_emi[idx].w;\n"
    "        *texA = sph_texA[idx]; *texB = sph_texB[idx];\n"
    "    } else if (kind == 1) {\n"
    "        *albedo_base = box_mat[idx].xyz; *emission = box_emi[idx].xyz;\n"
    "        *reflection = box_mat[idx].w; *shininess = box_emi[idx].w;\n"
    "        *texA = box_texA[idx]; *texB = box_texB[idx];\n"
    "    } else if (kind == 2) {\n"
    "        *albedo_base = plane_mat[idx].xyz; *emission = plane_emi[idx].xyz;\n"
    "        *reflection = plane_mat[idx].w; *shininess = plane_emi[idx].w;\n"
    "        *texA = plane_texA[idx]; *texB = plane_texB[idx];\n"
    "    } else if (kind == 4) {\n"
    "        *albedo_base = cyl_mat[idx].xyz; *emission = cyl_emi[idx].xyz;\n"
    "        *reflection = cyl_mat[idx].w; *shininess = cyl_emi[idx].w;\n"
    "        *texA = cyl_texA[idx]; *texB = cyl_texB[idx];\n"
    "    } else {\n"
    "        *albedo_base = bunny_mat.xyz; *emission = bunny_emi.xyz;\n"
    "        *reflection = bunny_mat.w; *shininess = bunny_emi.w;\n"
    "        *texA = (float4)(0.0f); *texB = (float4)(0.0f);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* path_radiance port: iterative MIS path tracer, max_depth 4, Russian\n"
    " * roulette from depth 2, fog support (scene_small has fog_density 0).\n"
    " * Shared per-pixel body for rt_main (full frame) and rt_tiles (hybrid\n"
    " * batches). per_sample_seed != 0 re-seeds per sample exactly like the CPU\n"
    " * tracer (pixel_seed + sample*0x9e3779b9) so a pixel's RNG stream never\n"
    " * depends on which device rendered it; rt_main keeps the legacy seed-once\n"
    " * stream. */\n"
    "float3 path_pixel(const int x, const int y, const int W, const int H,\n"
    "                   const int spp,\n"
    "                   const int sample_base,\n"
    "                  const float4 cam_pos, const float4 fwd, const float4 right,\n"
    "                  const float4 up, const float2 aspect_tan, const int4 counts,\n"
    "                  const int tri_count, const int light_count,\n"
    "                  const float4 fog, const float4 sun_dir, const float4 sun_col,\n"
    "                  __global const float4 *sph, __global const float4 *sph_mat,\n"
    "                  __global const float4 *sph_emi,\n"
    "                  __global const float4 *sph_texA, __global const float4 *sph_texB,\n"
    "                  __global const float4 *box_min, __global const float4 *box_max,\n"
    "                  __global const float4 *box_mat, __global const float4 *box_emi,\n"
    "                  __global const float4 *box_texA, __global const float4 *box_texB,\n"
    "                  __global const float4 *cyl_b, __global const float4 *cyl_h,\n"
    "                  __global const float4 *cyl_mat, __global const float4 *cyl_emi,\n"
    "                  __global const float4 *cyl_texA, __global const float4 *cyl_texB,\n"
    "                  __global const float4 *plane_pos, __global const float4 *plane_mat,\n"
    "                  __global const float4 *plane_emi,\n"
    "                  __global const float4 *plane_texA, __global const float4 *plane_texB,\n"
    "                  __global const float4 *lpos, __global const float4 *lcol,\n"
    "                  __global const float4 *lrad,\n"
    "                  __global const float *tris,\n"
    "                  __global const float4 *grid_a, __global const uint4 *grid_dims,\n"
    "                  __global const uint *grid_off, __global const uint *grid_tri,\n"
    "                  const float4 bunny_mat, const float4 bunny_emi,\n"
    "                  const int per_sample_seed) {\n"
    "    uint rng = pixel_seed(x, y);\n"
    "    float3 result = (float3)(0.0f);\n"
    "    int sample_count = spp < 1 ? 1 : spp;\n"
    "\n"
    "    for (int sample = 0; sample < sample_count; sample++) {\n"
    "        if (per_sample_seed != 0) rng = pixel_seed(x, y) +\n"
    "            (uint)(sample_base + sample) * 0x9e3779b9u;\n"
    "        float jx = rng_float(&rng);\n"
    "        float jy = rng_float(&rng);\n"
    "        float u = ((float)x + jx) / (float)W * 2.0f - 1.0f;\n"
    "        float v = 1.0f - ((float)y + jy) / (float)H * 2.0f;\n"
    "        float3 ro = cam_pos.xyz;\n"
    "        float3 rd = normalize(fwd.xyz + right.xyz * (u * aspect_tan.x)\n"
    "                              + up.xyz * (v * aspect_tan.y));\n"
    "\n"
    "        float3 throughput = (float3)(1.0f);\n"
    "        for (int depth = 0; depth <= MAX_DEPTH; depth++) {\n"
    "            struct Hit h = trace(ro, rd, counts, sph, box_min, box_max, cyl_b, cyl_h,\n"
    "                                 plane_pos, tri_count, tris,\n"
    "                                 grid_a, grid_dims, grid_off, grid_tri);\n"
    "            if (h.kind < 0) {\n"
    "                float3 environment = sky_color(rd, sun_dir, sun_col);\n"
    "                if (fog.x > 0.0f) {\n"
    "                    float transmittance = exp(-fog.x * 100.0f);\n"
    "                    result += throughput * fog.yzw * (1.0f - transmittance);\n"
    "                    environment *= transmittance;\n"
    "                }\n"
    "                result += throughput * environment;\n"
    "                break;\n"
    "            }\n"
    "            float3 p = ro + rd * h.t;\n"
    "            if (fog.x > 0.0f) {\n"
    "                float transmittance = exp(-fog.x * h.t);\n"
    "                result += throughput * fog.yzw * (1.0f - transmittance);\n"
    "                throughput *= transmittance;\n"
    "            }\n"
    "            float3 albedo_base, emission, albedo;\n"
    "            float reflection, shininess;\n"
    "            float4 texA, texB;\n"
    "            fetch_material(h.kind, h.idx, sph_mat, sph_emi, sph_texA, sph_texB,\n"
    "                           box_mat, box_emi, box_texA, box_texB,\n"
    "                           cyl_mat, cyl_emi, cyl_texA, cyl_texB,\n"
    "                           plane_mat, plane_emi, plane_texA, plane_texB,\n"
    "                           bunny_mat, bunny_emi,\n"
    "                           &albedo_base, &emission, &reflection, &shininess, &texA, &texB);\n"
    "            albedo = material_albedo(albedo_base, texA, texB, p);\n"
    "            if (h.kind == 2 && plane_pos[h.idx].x > 0.5f && (int)texA.x == 0) {\n"
    "                if ((((int)floor(p.x) + (int)floor(p.z)) & 1) != 0) albedo *= 0.35f;\n"
    "            }\n"
    "\n"
    "            result += throughput * emission;\n"
    "            /* sky is an environment emitter: small cosine-weighted estimate */\n"
    "            float3 environment = sky_color(h.n, sun_dir, sun_col);\n"
    "            result += throughput * (albedo * environment) * (0.08f / PI_F);\n"
    "\n"
    "            float3 view = -rd;\n"
    "            result += throughput * sample_direct_light(p, h.n, view, albedo,\n"
    "                reflection, shininess, &rng, counts, light_count, lpos, lcol, lrad,\n"
    "                sph, box_min, box_max, cyl_b, cyl_h, plane_pos, tri_count, tris,\n"
    "                grid_a, grid_dims, grid_off, grid_tri);\n"
    "\n"
    "            if (depth == MAX_DEPTH) break;\n"
    "            float bsdf_pdf;\n"
    "            float3 f, next_dir;\n"
    "            f = sample_bsdf(albedo, h.n, view, reflection, shininess, &rng,\n"
    "                            &next_dir, &bsdf_pdf);\n"
    "            if (bsdf_pdf <= 1e-6f) break;\n"
    "            float no_l = fmax(dot(h.n, next_dir), 0.0f);\n"
    "            if (no_l <= 0.0f) break;\n"
    "            throughput *= f * (no_l / bsdf_pdf);\n"
    "            if (depth >= 2) {\n"
    "                float q = clamp01(fmax(lum(throughput),\n"
    "                    fmax(throughput.x, fmax(throughput.y, throughput.z))));\n"
    "                if (rng_float(&rng) > q) break;\n"
    "                throughput *= 1.0f / fmax(q, 1e-3f);\n"
    "            }\n"
    "            ro = p + h.n * 1e-3f;\n"
    "            rd = next_dir;\n"
    "        }\n"
    "    }\n"
    "    return result / (float)sample_count;\n"
    "}\n"
    "\n"
    "__kernel void rt_main(__global float4 *out, __global const float *frame,\n"
    "                      __global const float4 *sph, __global const float4 *sph_mat,\n"
    "                      __global const float4 *sph_emi,\n"
    "                      __global const float4 *sph_texA, __global const float4 *sph_texB,\n"
    "                      __global const float4 *box_min, __global const float4 *box_max,\n"
    "                      __global const float4 *box_mat, __global const float4 *box_emi,\n"
    "                      __global const float4 *box_texA, __global const float4 *box_texB,\n"
    "                      __global const float4 *cyl_b, __global const float4 *cyl_h,\n"
    "                      __global const float4 *cyl_mat, __global const float4 *cyl_emi,\n"
    "                      __global const float4 *cyl_texA, __global const float4 *cyl_texB,\n"
    "                      __global const float4 *plane_pos, __global const float4 *plane_mat,\n"
    "                      __global const float4 *plane_emi,\n"
    "                      __global const float4 *plane_texA, __global const float4 *plane_texB,\n"
    "                      __global const float4 *lpos, __global const float4 *lcol,\n"
    "                      __global const float4 *lrad,\n"
    "                      __global const float *tris,\n"
    "                      __global const float4 *grid_a, __global const uint4 *grid_dims,\n"
    "                      __global const uint *grid_off, __global const uint *grid_tri) {\n"
    "    const int W = (int)frame[F_W], H = (int)frame[F_H];\n"
    "    const int x = (int)get_global_id(0);\n"
    "    const int y = (int)get_global_id(1);\n"
    "    if (x >= W || y >= H) return;\n"
    "\n"
    "    const float4 cam_pos = vload4(0, frame + F_CAM);\n"
    "    const float4 fwd = vload4(0, frame + F_FWD);\n"
    "    const float4 right = vload4(0, frame + F_RIGHT);\n"
    "    const float4 up = vload4(0, frame + F_UP);\n"
    "    const float2 aspect_tan = (float2)(frame[F_ASPECT], frame[F_ASPECT + 1]);\n"
    "    const int4 counts = (int4)((int)frame[F_COUNTS], (int)frame[F_COUNTS + 1],\n"
    "                               (int)frame[F_COUNTS + 2], (int)frame[F_COUNTS + 3]);\n"
    "    const int tri_count = (int)frame[F_TRI];\n"
    "    const int light_count = (int)frame[F_LIGHTS];\n"
    "    const float4 fog = vload4(0, frame + F_FOG);\n"
    "    const float4 sun_dir = vload4(0, frame + F_SUN_DIR);\n"
    "    const float4 sun_col = vload4(0, frame + F_SUN_COL);\n"
    "    const float4 bunny_mat = vload4(0, frame + F_BMAT);\n"
    "    const float4 bunny_emi = vload4(0, frame + F_BEMI);\n"
    "     const int spp = (int)frame[F_SPP];\n"
    "     const int sample_base = (int)frame[F_SAMPLE_BASE];\n"
    "     const int accumulating = (int)frame[F_ACCUM];\n"
    "\n"
    "     float3 result = path_pixel(x, y, W, H, spp, sample_base,\n"
    "                               cam_pos, fwd, right, up, aspect_tan, counts,\n"
    "                               tri_count, light_count, fog, sun_dir, sun_col,\n"
    "                               sph, sph_mat, sph_emi, sph_texA, sph_texB,\n"
    "                               box_min, box_max, box_mat, box_emi, box_texA, box_texB,\n"
    "                               cyl_b, cyl_h, cyl_mat, cyl_emi, cyl_texA, cyl_texB,\n"
    "                               plane_pos, plane_mat, plane_emi, plane_texA, plane_texB,\n"
    "                               lpos, lcol, lrad, tris,\n"
    "                               grid_a, grid_dims, grid_off, grid_tri,\n"
    "                                bunny_mat, bunny_emi, accumulating ? 1 : 0);\n"
    "\n"
    "     const int o = y * W + x;\n"
    "     if (accumulating) {\n"
    "         const float old_count = (float)sample_base;\n"
    "         const float new_count = old_count + (float)(spp < 1 ? 1 : spp);\n"
    "         float3 old = out[o].xyz;\n"
    "         result = old_count > 0.0f\n"
    "             ? (old * old_count + result * (float)spp) / new_count\n"
    "             : result;\n"
    "     }\n"
    "     out[o] = (float4)(result, 1.0f);\n"
    "}\n"
    "\n"
    "/* Hybrid tile worker: one workgroup per tile (tile*tile work-items),\n"
    " * tile_batch holds (x0, y0) pairs in Morton order. Writes float4 HDR for\n"
    " * its pixels into the same film layout as rt_main; the host composites\n"
    " * CPU and GPU tiles and runs the shared post chain. Uses the CPU RNG\n"
    " * scheme (per_sample_seed = 1). */\n"
    "__kernel void rt_tiles(__global float4 *out, __global const float *frame,\n"
    "                       __global const float4 *sph, __global const float4 *sph_mat,\n"
    "                       __global const float4 *sph_emi,\n"
    "                       __global const float4 *sph_texA, __global const float4 *sph_texB,\n"
    "                       __global const float4 *box_min, __global const float4 *box_max,\n"
    "                       __global const float4 *box_mat, __global const float4 *box_emi,\n"
    "                       __global const float4 *box_texA, __global const float4 *box_texB,\n"
    "                       __global const float4 *cyl_b, __global const float4 *cyl_h,\n"
    "                       __global const float4 *cyl_mat, __global const float4 *cyl_emi,\n"
    "                       __global const float4 *cyl_texA, __global const float4 *cyl_texB,\n"
    "                       __global const float4 *plane_pos, __global const float4 *plane_mat,\n"
    "                       __global const float4 *plane_emi,\n"
    "                       __global const float4 *plane_texA, __global const float4 *plane_texB,\n"
    "                       __global const float4 *lpos, __global const float4 *lcol,\n"
    "                       __global const float4 *lrad,\n"
    "                       __global const float *tris,\n"
    "                       __global const float4 *grid_a, __global const uint4 *grid_dims,\n"
    "                       __global const uint *grid_off, __global const uint *grid_tri,\n"
    "                       __global const int *tile_batch, const int tile) {\n"
    "    const int lid = (int)get_local_id(0);\n"
    "    const int tile_id = (int)get_group_id(0);\n"
    "    const int W = (int)frame[F_W], H = (int)frame[F_H];\n"
    "    const int x = tile_batch[tile_id * 2] + lid % tile;\n"
    "    const int y = tile_batch[tile_id * 2 + 1] + lid / tile;\n"
    "    if (x >= W || y >= H) return;\n"
    "\n"
    "    const float4 cam_pos = vload4(0, frame + F_CAM);\n"
    "    const float4 fwd = vload4(0, frame + F_FWD);\n"
    "    const float4 right = vload4(0, frame + F_RIGHT);\n"
    "    const float4 up = vload4(0, frame + F_UP);\n"
    "    const float2 aspect_tan = (float2)(frame[F_ASPECT], frame[F_ASPECT + 1]);\n"
    "    const int4 counts = (int4)((int)frame[F_COUNTS], (int)frame[F_COUNTS + 1],\n"
    "                               (int)frame[F_COUNTS + 2], (int)frame[F_COUNTS + 3]);\n"
    "    const int tri_count = (int)frame[F_TRI];\n"
    "    const int light_count = (int)frame[F_LIGHTS];\n"
    "    const float4 fog = vload4(0, frame + F_FOG);\n"
    "    const float4 sun_dir = vload4(0, frame + F_SUN_DIR);\n"
    "    const float4 sun_col = vload4(0, frame + F_SUN_COL);\n"
    "    const float4 bunny_mat = vload4(0, frame + F_BMAT);\n"
    "    const float4 bunny_emi = vload4(0, frame + F_BEMI);\n"
    "    const int spp = (int)frame[F_SPP];\n"
    "\n"
    "     float3 result = path_pixel(x, y, W, H, spp, 0,\n"
    "                               cam_pos, fwd, right, up, aspect_tan, counts,\n"
    "                               tri_count, light_count, fog, sun_dir, sun_col,\n"
    "                               sph, sph_mat, sph_emi, sph_texA, sph_texB,\n"
    "                               box_min, box_max, box_mat, box_emi, box_texA, box_texB,\n"
    "                               cyl_b, cyl_h, cyl_mat, cyl_emi, cyl_texA, cyl_texB,\n"
    "                               plane_pos, plane_mat, plane_emi, plane_texA, plane_texB,\n"
    "                               lpos, lcol, lrad, tris,\n"
    "                               grid_a, grid_dims, grid_off, grid_tri,\n"
    "                               bunny_mat, bunny_emi, 1);\n"
    "    out[y * W + x] = (float4)(result, 1.0f);\n"
    "}\n"
    "\n"
    "/* ------------------------------------------------------------------ post\n"
    " * GPU port of the CPU post chain (postprocess_hdr / exposed_hdr), kept\n"
    " * mathematically identical including the bloom's per-ring nested division.\n"
    " * Adaptation state stays on the host via rt_exposure_from_logavg(). */\n"
    "\n"
    "/* Sum of log(delta + L) over all pixels; one partial per workgroup. Host\n"
    " * sums the partials as doubles and calls rt_exposure_from_logavg(). */\n"
    "__kernel void rt_logavg(__global const float4 *hdr, const int npix,\n"
    "                        __local float *lsum, __global float *partials) {\n"
    "    const int gid = (int)get_global_id(0);\n"
    "    const int gsz = (int)get_global_size(0);\n"
    "    const int lid = (int)get_local_id(0);\n"
    "    float acc = 0.0f;\n"
    "    for (int i = gid; i < npix; i += gsz) {\n"
    "        float l = fmax(lum(hdr[i].xyz), 0.0f);\n"
    "        acc += log(1e-4f + l);\n"
    "    }\n"
    "    lsum[lid] = acc;\n"
    "    barrier(CLK_LOCAL_MEM_FENCE);\n"
    "    for (int s = (int)get_local_size(0) >> 1; s > 0; s >>= 1) {\n"
    "        if (lid < s) lsum[lid] += lsum[lid + s];\n"
    "        barrier(CLK_LOCAL_MEM_FENCE);\n"
    "    }\n"
    "    if (lid == 0) partials[get_group_id(0)] = lsum[0];\n"
    "}\n"
    "\n"
    "__constant int   BLOOM_OFFSETS[4] = { 1, 2, 4, 8 };\n"
    "__constant float BLOOM_WEIGHTS[4] = { 0.20f, 0.10f, 0.055f, 0.025f };\n"
    "\n"
    "uchar srgb_byte(float x) {\n"
    "    if (!(x > 0.0f)) return 0;\n"
    "    x = fmax(x, 0.0f);\n"
    "    float e = x <= 0.0031308f\n"
    "        ? 12.92f * x\n"
    "        : 1.055f * powr(x, 1.0f / 2.4f) - 0.055f;\n"
    "    if (e > 1.0f) e = 1.0f;\n"
    "    return convert_uchar_sat(e * 255.0f + 0.5f);\n"
    "}\n"
    "\n"
    "/* Tone map the internal HDR film to 8-bit sRGB (rgba). */\n"
    "__kernel void rt_post(__global const float4 *hdr, __global uchar4 *rgb8,\n"
    "                      const int W, const int H, const float exposure) {\n"
    "    const int x = (int)get_global_id(0);\n"
    "    const int y = (int)get_global_id(1);\n"
    "    if (x >= W || y >= H) return;\n"
    "\n"
    "    float3 bloom = (float3)(0.0f);\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        const int distance = BLOOM_OFFSETS[i];\n"
    "        int samples = 0;\n"
    "        const int px[4] = { x - distance, x + distance, x, x };\n"
    "        const int py[4] = { y, y, y - distance, y + distance };\n"
    "        for (int k = 0; k < 4; k++) {\n"
    "            if (px[k] < 0 || px[k] >= W || py[k] < 0 || py[k] >= H) continue;\n"
    "            float3 s = hdr[py[k] * W + px[k]].xyz * exposure;\n"
    "            if (lum(s) <= 1.0f) continue;\n"
    "            bloom += s * BLOOM_WEIGHTS[i];\n"
    "            samples++;\n"
    "        }\n"
    "        if (samples > 0) bloom /= (float)samples;\n"
    "    }\n"
    "    float3 c = hdr[y * W + x].xyz * exposure + bloom;\n"
    "    c = c / (1.0f + c);\n"
    "    rgb8[y * W + x] = (uchar4)(srgb_byte(c.x), srgb_byte(c.y), srgb_byte(c.z), 255);\n"
    "}\n"
    "\n"
    "/* ---------------------------------------------------------------- upscale\n"
    " * Spatial upscale of the tone-mapped film: Catmull-Rom bicubic, edge-clamped\n"
    " * sampling, then optional CAS sharpen as a separate pass. */\n"
    "\n"
    "float4 cr_weights(const float t) {\n"
    "    const float t2 = t * t;\n"
    "    const float t3 = t2 * t;\n"
    "    return (float4)(-0.5f * t3 + t2 - 0.5f * t,\n"
    "                     1.5f * t3 - 2.5f * t2 + 1.0f,\n"
    "                    -1.5f * t3 + 2.0f * t2 + 0.5f * t,\n"
    "                     0.5f * t3 - 0.5f * t2);\n"
    "}\n"
    "\n"
    "float3 cr_fetch(__global const uchar4 *src, const int IW, const int IH,\n"
    "                int ix, int iy) {\n"
    "    ix = clamp(ix, 0, IW - 1);\n"
    "    iy = clamp(iy, 0, IH - 1);\n"
    "    uchar4 s = src[iy * IW + ix];\n"
    "    return convert_float3(s.xyz);\n"
    "}\n"
    "\n"
    "float3 cr_sample(__global const uchar4 *src, const int IW, const int IH,\n"
    "                 const float fx, const float fy) {\n"
    "    const float flx = floor(fx), fly = floor(fy);\n"
    "    const float4 wx = cr_weights(fx - flx);\n"
    "    const float4 wy = cr_weights(fy - fly);\n"
    "    const int x0 = (int)flx - 1;\n"
    "    const int y0 = (int)fly - 1;\n"
    "    float3 acc = (float3)(0.0f);\n"
    "    for (int j = 0; j < 4; j++) {\n"
    "        float3 row = (float3)(0.0f);\n"
    "        for (int i = 0; i < 4; i++) {\n"
    "            row += cr_fetch(src, IW, IH, x0 + i, y0 + j) * wx[i];\n"
    "        }\n"
    "        acc += row * wy[j];\n"
    "    }\n"
    "    return acc;\n"
    "}\n"
    "\n"
    "__kernel void rt_upscale(__global const uchar4 *src, __global uchar4 *dst,\n"
    "                         const int IW, const int IH, const int W, const int H) {\n"
    "    const int x = (int)get_global_id(0);\n"
    "    const int y = (int)get_global_id(1);\n"
    "    if (x >= W || y >= H) return;\n"
    "    const float fx = ((float)x + 0.5f) * ((float)IW / (float)W) - 0.5f;\n"
    "    const float fy = ((float)y + 0.5f) * ((float)IH / (float)H) - 0.5f;\n"
    "    float3 c = cr_sample(src, IW, IH, fx, fy);\n"
    "    c = clamp(c, (float3)(0.0f), (float3)(255.0f));\n"
    "    dst[y * W + x] = (uchar4)(convert_uchar_sat(c.x + 0.5f),\n"
    "                              convert_uchar_sat(c.y + 0.5f),\n"
    "                              convert_uchar_sat(c.z + 0.5f), 255);\n"
    "}\n"
    "\n"
    "/* CAS-style sharpen with halo suppression (clamped to the 5-tap range). */\n"
    "__kernel void rt_cas(__global const uchar4 *src, __global uchar4 *dst,\n"
    "                     const int W, const int H, const float amount) {\n"
    "    const int x = (int)get_global_id(0);\n"
    "    const int y = (int)get_global_id(1);\n"
    "    if (x >= W || y >= H) return;\n"
    "    const int xm = max(x - 1, 0), xp = min(x + 1, W - 1);\n"
    "    const int ym = max(y - 1, 0), yp = min(y + 1, H - 1);\n"
    "    float3 c  = convert_float3(src[y * W + x].xyz);\n"
    "    float3 n1 = convert_float3(src[y * W + xm].xyz);\n"
    "    float3 n2 = convert_float3(src[y * W + xp].xyz);\n"
    "    float3 n3 = convert_float3(src[ym * W + x].xyz);\n"
    "    float3 n4 = convert_float3(src[yp * W + x].xyz);\n"
    "    float3 blur = (n1 + n2 + n3 + n4) * 0.25f;\n"
    "    float3 s = c + (c - blur) * amount;\n"
    "    float3 lo = fmin(c, fmin(n1, fmin(n2, fmin(n3, n4))));\n"
    "    float3 hi = fmax(c, fmax(n1, fmax(n2, fmax(n3, n4))));\n"
    "    s = clamp(s, lo, hi);\n"
    "    dst[y * W + x] = (uchar4)(convert_uchar_sat(s.x + 0.5f),\n"
    "                              convert_uchar_sat(s.y + 0.5f),\n"
    "                              convert_uchar_sat(s.z + 0.5f), 255);\n"
    "}\n"
    "\n"
    "/* Zero-copy present (cl_khr_gl_sharing): copy the final RGBA8 frame into the\n"
    " * GL-shared texture so the viewer draws it without a readback round-trip. */\n"
    "__kernel void rt_present(__global const uchar4 *src, __write_only image2d_t dst,\n"
    "                         const int W, const int H) {\n"
    "    const int x = (int)get_global_id(0);\n"
    "    const int y = (int)get_global_id(1);\n"
    "    if (x >= W || y >= H) return;\n"
    "     const uchar4 c = src[y * W + x];\n"
    "     /* GL_RGBA8 is a normalized image: integer writes produce black on the\n"
    "      * Intel sharing path, while normalized float writes preserve RGBA8. */\n"
    "     write_imagef(dst, (int2)(x, y),\n"
    "                  (float4)((float)c.x / 255.0f, (float)c.y / 255.0f,\n"
    "                           (float)c.z / 255.0f, 1.0f));\n"
    "}\n"
    "\n"
    ;
#endif

